export const LANG_ES_TRANS = {
    'available': 'Disponible',
    'address': 'Dirección',
    'buyDate': 'Fecha Compra',
    'codPostal': 'Cod Postal',
    'chooseImage': 'Elegir Imagen',
    'city': 'Población',
    'configuration': 'Configuración',
    'download': 'Descargar',
    'sellDate': 'Fecha de Venta',
    'state': 'Provincia',
    'language': 'Idioma',
    'removeImage': 'Borrar Imagen',
    'editing': 'Editando',
    'es': 'Español',
    'en': 'Inglés',
    'fr': 'Francés',
    'emptyListError': 'Lista de artículos vacía',
    'home': 'Inicio',
    'edit': 'Editar',
    'format': 'Formato',
    'platform': 'Plataforma',
    'platforms': 'Plataformas',
    'price': 'Precio',
    'print': 'Imprimir',
    'client': 'Cliente',
    'clients': 'Clientes',
    'clientRequiredError': 'Debe seleccionar un cliente',
    'game': 'Juego',
    'games': 'Juegos',
    'sale': 'Venta',
    'sold': 'Vendido',
    'saleDate': 'Fecha de Venta',
    'salePrice': 'Precio Venta',
    'salesCheck': 'Facturas',
    'salesCheckDate': 'Fecha Factura',
    'rent': 'Alquiler',
    'rentDate': 'Fecha de Alquiler',
    'rented': 'Alquilado',
    'rentPrice': 'Precio Alquiler',
    'returnDate': 'Fecha de Devolución',
    'help': 'Ayuda',
    'homeQuest1': '¿Qué es GamerStore?',
    'homeAnswer1': 'GamerStore es el proyecto de fin de Ciclo Formativo en Desarrollo de Aplicaciones Web.',
    'homeQuest2': 'Funcionalidad:',
    'homeAnswer2': 'GamerStore es un Aplicativo Web para gestionar una tienda de Alquiler y Venta de Juegos y Películas.',
    'homeQuest3': 'Especificaciones Técnicas:',
    'homeAnswer3': 'Desarrollado en un entorno Linux (Fedora) utilizando en su totalidad software libre. Para guardar los datos se utiliza MariaDB. El Back-End está desarrollado en Java, utilizando el framework Spring. El Front-End está desarrollado con el framework Angular.',
    'developedBy': 'Desarrollado por',
    'items': 'Artículos',
    'name': 'Nombre',
    'number': 'Número',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'erase': 'Borrar',
    'add': 'Añadir',
    'search': 'Buscar',
    'surname': 'Apellidos',
    'dni': 'DNI',
    'telephone': 'Teléfono',
    'found': 'Encontrado',
    'of': 'de',
    'cover': 'Carátula',
    'quantity': 'Cantidad',
    'rent_price': 'Precio Alquiler',
    'rent_available': 'Disponible Alquiler',
    'sale_price': 'Precio Venta',
    'sale_available': 'Disponible Venta',
    'scannerRequiredError': 'No Disponible',
    'code': 'Código',
    'close': 'Cerrar',
    'total': 'Total',
    'login': 'Iniciar Sesión',
    'logout': 'Cerrar Sesión',
    'signup': 'Registrarse',
    'emailExist': 'El email ya existe.',
    'emailError': 'Email incorrecto.',
    'passwError': 'Password incorrecto.',

    'plataformasHelp': 'En esta pantalla debe registrar las diferentes plataformas para las que se venden los artículos (ej. Play Station, XBoX, etc.).',
    'juegosHelp': 'En esta pantalla se registran los juegos, independientemente de la plataforma para los que se realizan.',
    'articulosHelp': 'Relación de artículos disponibles para la venta y alquiler.',
    'clientesHelp': 'Relación de clientes. Se necesita tener al cliente registrado para poder realizar una venta o alquiler.',
    'alquileresHelp': 'Se puede localizar un artículo pulsando en el boton Scanear y pasar el código de barras por la cámara. Cuando ya estén los articulos en la lista Alquilado, pulsar el botón Guardar para finalizar.',
    'ventasHelp': 'Se puede localizar un artículo pulsando en el boton Scanear y pasar el código de barras por la cámara. Cuando ya estén los articulos en la lista Vendido, pulsar el botón Guardar para finalizar.',
    'facturasHelp': 'Resumen de facturación por cliente.'
};
