export const LANG_FR_TRANS = {
    'available': 'Disponible',
    'address': 'Adresse',
    'buyDate': "Date d'achat",
    'codPostal': 'Code postal',
    'chooseImage': 'Choisir une image',
    'city': 'Ville',
    'configuration': 'La configuration',
    'download': 'Télécharger',
    'sellDate': 'Date de vente',
    'state': 'Province',
    'language': 'Langage',
    'removeImage': "Supprimer l'image",
    'editing': 'Édition',
    'es': 'Espagnol',
    'en': 'Anglais',
    'fr': 'Le français',
    'emptyListError': 'Liste des articles vides',
    'home': 'Accueil',
    'edit': 'Éditer',
    'format': 'Le format',
    'platform': 'Plate-forme',
    'platforms': 'Plateformes',
    'price': 'Prix',
    'print': 'Imprimer',
    'client': 'Client',
    'clients': 'Les clients',
    'clientRequiredError': 'Vous devez sélectionner un client',
    'game': 'Jeu',
    'games': 'Jeux',
    'sale': 'Vente',
    'sold': 'Vendu',
    'saleDate': 'Date de vente',
    'salePrice': 'Prix de vente',
    'salesCheck': 'Factures',
    'salesCheckDate': 'Date de facturation',
    'rent': 'La location',
    'rentDate': 'Date de location',
    'rented': 'Loué',
    'rentPrice': 'Prix de location',
    'returnDate': 'Date de retour',
    'help': "L'aide",
    'homeQuest1': "Qu'est-ce que GamerStore?",
    'homeAnswer1': "GamerStore est le projet final du cycle de formation en développement d'applications Web.",
    'homeQuest2': 'La fonctionnalité:',
    'homeAnswer2': 'GamerStore est une application Web permettant de gérer une boutique de location et de vente de jeux et de films.',
    'homeQuest3': 'Spécifications techniques:',
    'homeAnswer3': 'Développé dans un environnement Linux (Fedora) en utilisant le logiciel libre dans son intégralité. Pour sauvegarder les données, MariaDB est utilisé. Le back-end est développé en Java, en utilisant le framework Spring. Le Front-End est développé avec le cadre angulaire.',
    'developedBy': 'Développé par',
    'items': 'Des articles',
    'name': 'Nom',
    'number': 'Le numéro',
    'save': 'Sauvegarder',
    'cancel': 'Annuler',
    'erase': 'Supprimer',
    'add': 'Ajouter',
    'search': 'Recherche',
    'surname': 'Nom de famille',
    'dni': 'ID',
    'telephone': 'Téléphone',
    'found': 'Trouvé',
    'of': 'de',
    'cover': 'Couverture',
    'quantity': 'Montant',
    'rent_price': 'Prix de location',
    'rent_available': 'Loyer disponible',
    'sale_price': 'Prix de vente',
    'sale_available': 'Vente disponible',
    'scannerRequiredError': 'Non disponible',
    'code': 'Code',
    'close': 'Fermer',
    'total': 'Total',
    'login': 'Commencer la session',
    'logout': 'Fermer la session',
    'signup': "S'inscrire",
    'emailExist': 'Le mail existe déjà.',
    'emailError': 'Email incorrect.',
    'passwError': 'Mot de passe incorrect.',

    'plataformasHelp': 'Sur cet écran, vous devez enregistrer les différentes plates-formes pour lesquelles les articles sont vendus (par exemple Play Station, XBoX, etc.).',
    'juegosHelp': 'Sur cet écran, les jeux sont enregistrés, quelle que soit la plate-forme pour laquelle ils sont conçus.',
    'articulosHelp': 'Liste des articles disponibles à la vente et à la location.',
    'clientesHelp': 'Relation client Vous devez avoir le client enregistré pour pouvoir effectuer une vente ou une location.',
    'alquileresHelp': 'Vous pouvez localiser un article en cliquant sur le bouton Numériser et en passant le code à barres dans la caméra. Lorsque les articles sont déjà dans la liste louée, appuyez sur le bouton Enregistrer pour terminer.',
    'ventasHelp': 'Vous pouvez localiser un article en cliquant sur le bouton Numériser et en passant le code à barres dans la caméra. Lorsque les articles sont déjà dans la liste Vendu, appuyez sur le bouton Enregistrer pour terminer.',
    'facturasHelp': 'Récapitulatif de facturation par client.'
};
