export const LANG_EN_TRANS = {
    'available': 'Available',
    'address': 'Address',
    'buyDate': 'Buy Date',
    'codPostal': 'Cod',
    'chooseImage': 'Choose Image',
    'city': 'City',
    'configuration': 'Configuration',
    'salesCheck': 'Sales Check',
    'sellDate': 'Sell Date',
    'state': 'State',
    'language': 'Language',
    'removeImage': 'Remove Image',
    'editing': 'Editing',
    'es': 'Spanish',
    'en': 'English',
    'home': 'Home',
    'edit': 'Edit',
    'format': 'Format',
    'platform': 'Plataform',
    'platforms': 'Platforms',
    'price': 'Price',
    'print': 'Print',
    'client': 'Client',
    'clients': 'Clients',
    'clientRequiredError': 'You must select a client',
    'game': 'Game',
    'games': 'Games',
    'sale': 'Sale',
    'salePrice': 'Sale Price',
    'rent': 'Rent',
    'rentDate': 'Rent Date',
    'rented': 'Rented',
    'rentPrice': 'Rent Price',
    'returnDate': 'Return Date',
    'homeQuest1': 'What is GamerStore?',
    'homeAnswer1': 'GamerStore is the final project of the Training Cycle in Web Application Development.',
    'homeQuest2': 'Functionality:',
    'homeAnswer2': 'GamerStore is a Web Application to manage a Games and Movies Rental and Sale shop.',
    'homeQuest3': 'Technical specifications:',
    'homeAnswer3': 'Developed in a Linux environment (Fedora) using free software in its entirety. To save the data MariaDB is used. The Back-End is developed in Java, using the Spring framework. The Front-End is developed with the Angular framework.',
    'developedBy': 'Developed by',
    'items': 'Items',
    'name': 'Name',
    'save': 'Save',
    'cancel': 'Cancel',
    'erase': 'Erase',
    'add': 'Add',
    'search': 'Search',
    'surname': 'Surname',
    'dni': 'DNI',
    'telephone': 'Telephone',
    'found': 'Found',
    'of': 'of',
    'cover': 'Cover',
    'quantity': 'Quantity',
    'rent_price': 'Rent Price',
    'rent_available': 'Rent Available',
    'sale_price': 'Sale Price',
    'sale_available': 'Sale Available',
    'code': 'Code'
};
