export const LANG_ES_TRANS = {
    'available': 'Disponible',
    'address': 'Dirección',
    'buyDate': 'Fecha Compra',
    'codPostal': 'Cod Postal',
    'chooseImage': 'Elegir Imagen',
    'city': 'Población',
    'configuration': 'Configuración',
    'sellDate': 'Fecha de Venta',
    'state': 'Provincia',
    'language': 'Idioma',
    'removeImage': 'Borrar Imagen',
    'editing': 'Editando',
    'es': 'Español',
    'en': 'Inglés',
    'emptyListError': 'Lista de artículos vacía',
    'home': 'Inicio',
    'edit': 'Editar',
    'format': 'Formato',
    'platform': 'Plataforma',
    'platforms': 'Plataformas',
    'price': 'Precio',
    'print': 'Imprimir',
    'client': 'Cliente',
    'clients': 'Clientes',
    'clientRequiredError': 'Debe seleccionar un cliente',
    'game': 'Juego',
    'games': 'Juegos',
    'sale': 'Venta',
    'salePrice': 'Precio Venta',
    'salesCheck': 'Facturas',
    'rent': 'Alquiler',
    'rentDate': 'Fecha de Alquiler',
    'rented': 'Alquilado',
    'rentPrice': 'Precio Alquiler',
    'returnDate': 'Fecha de Devolución',
    'homeQuest1': '¿Qué es GamerStore?',
    'homeAnswer1': 'GamerStore es el proyecto de fin de Ciclo Formativo en Desarrollo de Aplicaciones Web.',
    'homeQuest2': 'Funcionalidad:',
    'homeAnswer2': 'GamerStore es un Aplicativo Web para gestionar una tienda de Alquiler y Venta de Juegos y Películas.',
    'homeQuest3': 'Especificaciones Técnicas:',
    'homeAnswer3': 'Desarrollado en un entorno Linux (Fedora) utilizando en su totalidad software libre. Para guardar los datos se utiliza MariaDB. El Back-End está desarrollado en Java, utilizando el framework Spring. El Front-End está desarrollado con el framework Angular.',
    'developedBy': 'Desarrollado por',
    'items': 'Artículos',
    'name': 'Nombre',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'erase': 'Borrar',
    'add': 'Añadir',
    'search': 'Buscar',
    'surname': 'Apellidos',
    'dni': 'DNI',
    'telephone': 'Teléfono',
    'found': 'Encontrado',
    'of': 'de',
    'cover': 'Carátula',
    'quantity': 'Cantidad',
    'rent_price': 'Precio Alquiler',
    'rent_available': 'Disponible Alquiler',
    'sale_price': 'Precio Venta',
    'sale_available': 'Disponible Venta',
    'scannerRequiredError': 'No Disponible',
    'code': 'Código'
};
