export const LANG_EN_TRANS = {
    'available': 'Available',
    'address': 'Address',
    'buyDate': 'Buy Date',
    'codPostal': 'Cod',
    'chooseImage': 'Choose Image',
    'city': 'City',
    'configuration': 'Configuration',
    'download': 'Download',
    'salesCheck': 'Sales Check',
    'salesCheckDate': 'Sales Check Date',
    'sellDate': 'Sell Date',
    'state': 'State',
    'language': 'Language',
    'removeImage': 'Remove Image',
    'editing': 'Editing',
    'es': 'Spanish',
    'en': 'English',
    'fr': 'French',
    'emptyListError': 'List of articles empty',
    'home': 'Home',
    'edit': 'Edit',
    'format': 'Format',
    'platform': 'Plataform',
    'platforms': 'Platforms',
    'price': 'Price',
    'print': 'Print',
    'client': 'Client',
    'clients': 'Clients',
    'clientRequiredError': 'You must select a client',
    'game': 'Game',
    'games': 'Games',
    'sale': 'Sale',
    'sold': 'Sold',
    'saleDate': 'Sale Date',
    'salePrice': 'Sale Price',
    'rent': 'Rent',
    'rentDate': 'Rent Date',
    'rented': 'Rented',
    'rentPrice': 'Rent Price',
    'returnDate': 'Return Date',
    'help': 'Help',
    'homeQuest1': 'What is GamerStore?',
    'homeAnswer1': 'GamerStore is the final project of the Training Cycle in Web Application Development.',
    'homeQuest2': 'Functionality:',
    'homeAnswer2': 'GamerStore is a Web Application to manage a Games and Movies Rental and Sale shop.',
    'homeQuest3': 'Technical specifications:',
    'homeAnswer3': 'Developed in a Linux environment (Fedora) using free software in its entirety. To save the data MariaDB is used. The Back-End is developed in Java, using the Spring framework. The Front-End is developed with the Angular framework.',
    'developedBy': 'Developed by',
    'items': 'Items',
    'name': 'Name',
    'number': 'Number',
    'save': 'Save',
    'cancel': 'Cancel',
    'erase': 'Erase',
    'add': 'Add',
    'search': 'Search',
    'surname': 'Surname',
    'dni': 'DNI',
    'telephone': 'Telephone',
    'found': 'Found',
    'of': 'of',
    'cover': 'Cover',
    'quantity': 'Quantity',
    'rent_price': 'Rent Price',
    'rent_available': 'Rent Available',
    'sale_price': 'Sale Price',
    'sale_available': 'Sale Available',
    'scannerRequiredError': 'Not Available',
    'code': 'Code',
    'close': 'Close',
    'total': 'Total',
    'login': 'Login',
    'logout': 'Logout',
    'signup': 'Sign Up',
    'emailExist': 'This E-mail already exists.',
    'emailError': 'Wrong email.',
    'passwError': 'Wrong password.',

    'plataformasHelp': 'On this screen you must register the different platforms for which the items are sold (eg Play Station, XBoX, etc.).',
    'juegosHelp': 'In this screen the games are registered, independently of the platform for which they are made.',
    'articulosHelp': 'List of items available for sale and rent.',
    'clientesHelp': 'Customer list. You need to have the registered customer to be able to make a sale or rent.',
    'alquileresHelp': 'An article can be located by clicking on the Scan button and passing the barcode through the camera. When the items are in the list, press the save button to finish.',
    'ventasHelp': 'An article can be located by clicking on the Scan button and passing the barcode through the camera. When the items are in the list, press the save button to finish.',
    'facturasHelp': 'Billing summary by customer.',

    'deleteWarning': 'If you delete the record, the related data will also be deleted.'
};
